export let formValues = {
  name: undefined,
  surname: undefined,
  date: undefined,
  street: undefined,
  houseNumber: undefined,
  flatNumber: undefined,
  payment: "card",
  gift: [],
};

export let inputTypes = {
  name: {
    classList: "label__text name__label",
    title: "Name",
    type: "text",
    id: "name__input",
    name: "name",
    placeholder: "Name",
    isRequired: true,
    ariaLabel: "name",
    minLength: 4,
  },
  surname: {
    classList: "label__text surname__label",
    title: "Surname",
    type: "text",
    id: "surname__input",
    name: "surname",
    placeholder: "Surname",
    isRequired: true,
    ariaLabel: "surname",
    minLength: 5,
  },
  date: {
    classList: "date__label label__text",
    title: "Choose date",
    type: "date",
    id: "date__input",
    name: "date",
    isRequired: true,
    ariaLabel: "date",
  },
  street: {
    classList: "label__text street__label",
    title: "Street",
    type: "text",
    id: "street__input",
    name: "street",
    placeholder: "Street",
    isRequired: true,
    ariaLabel: "street",
    minLength: 5,
  },
  house: {
    classList: "label__text house-number__label",
    title: "House number",
    type: "number",
    id: "house-number__input",
    name: "house-number",
    placeholder: "House-number",
    isRequired: true,
    ariaLabel: "house-number",
    minLength: 1,
    min: 0,
  },
  flat: {
    classList: "label__text flat-number__label",
    title: "Flat number",
    type: "number",
    id: "flat-number__input",
    name: "flat-number",
    placeholder: "Flat-number",
    isRequired: true,
    ariaLabel: "flat-number",
    minLength: 1,
    min: 0,
  },
};
